// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ6v5JJx4X2dtLGlap-Vi2iZET1mXH4mw',
    appId: '1:289520619023:web:b2b1b9bc07a9cf70969d7a',
    messagingSenderId: '289520619023',
    projectId: 'djani-gpt',
    authDomain: 'djani-gpt.firebaseapp.com',
    storageBucket: 'djani-gpt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2PRjrVOuBm0D0LAZABC6jynuiA1L_q4',
    appId: '1:289520619023:android:da210299bdcac5e2969d7a',
    messagingSenderId: '289520619023',
    projectId: 'djani-gpt',
    storageBucket: 'djani-gpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25Zhe87h8Dcor3quMJ5RafhnQoyOX4Gk',
    appId: '1:289520619023:ios:29a891b5bd8e2baa969d7a',
    messagingSenderId: '289520619023',
    projectId: 'djani-gpt',
    storageBucket: 'djani-gpt.appspot.com',
    iosBundleId: 'com.example.iutAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25Zhe87h8Dcor3quMJ5RafhnQoyOX4Gk',
    appId: '1:289520619023:ios:68dace363f7483d3969d7a',
    messagingSenderId: '289520619023',
    projectId: 'djani-gpt',
    storageBucket: 'djani-gpt.appspot.com',
    iosBundleId: 'com.example.iutAssistant.RunnerTests',
  );
}
